### PR TITLE
Update meld and gnome runtime

### LINKED ISSUE #45: Update runtime to GNOME 46

### PR DESCRIPTION
**Pull request by xduugu**
Fixes #45

### CODE REVIEW

**Comment by xduugu** [comment]
Hey @hfiguiere, please have a look at this PR and merge it if everything is fine.

**Comment by hfiguiere** [comment]
did you test it?

**Comment by x80486** [comment]
Works fine...you can go ahead and merge.

image

**Comment by xduugu** [comment]
@hfiguiere, yes, I tested folder and file comparison.

**Pull request merged**
