### PR TITLE
Update to 3.19

### PR DESCRIPTION
**Pull request by nedrichards**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by TingPing** [comment]
Do they not follow gnome versioning for odd releases?

**Comment by nedrichards** [comment]
Not based on my reading of the news file: https://download.gnome.org/sources/meld/3.19/meld-3.19.0.news

**Comment by kaiw** [comment]
I'm not entirely sure what the question is here, but if it's about whether odd numbered releases are unstable, then yes they are.

Generally Meld's unstable releases are very usable, but I'd suggest probably not enough for flathub IMO.

**Comment by nedrichards** [comment]
Apologies

**Pull request closed without merging**
