### PR TITLE
Add Git

### PR DESCRIPTION
**Pull request by p1u3o**
This adds Git to the Flatpak.

I also added some formatting changes that makes it match the other GNOME flatpaks.

### CODE REVIEW

**Comment by Lctrs** [comment]
You should use `INSTALL_SYMLINKS=1` `build-options.env` to greatly reduce compile time and install size.

**Comment by p1u3o** [comment]
I've actually been thinking it's probably easier to just copy the git binary from the sdk to /app at runtime.

**Comment by p1u3o** [comment]
I've swapped this to copying git from the sdk, it works fine.

**Comment by bilelmoussaoui** [comment]
Thanks @p1u3o

**Pull request merged**
