### PR TITLE
Update runtime to 3.38, app to 3.21.0

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by FakeShemp** [comment]
bot, build

**Comment by kaiw** [comment]
3.21.0 is an unstable development release, so this bump probably shouldn't
be pushed out to users. The runtime update *should* work best I know,
however.

**Comment by Eonfge** [comment]
I'm not trying to cut you short, but I made a runtime update in #26 so I hope you can rebase your pending changes on that. Also, check #24 because there is a name-change in the pipeline, deprecating this repository

**Comment by bilelmoussaoui** [comment]
> I'm not trying to cut you short, but I made a runtime update in #26 so I hope you can rebase your pending changes on that. Also, check #24 because there is a name-change in the pipeline, deprecating this repository

No need to deprecate the repository in this case.

**Pull request closed without merging**
