### PR TITLE
Upgrade to 3.19

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by kaiw** [comment]
This is a development release, not a stable one. I thought that flathub was intended to be stable-only?

**Comment by bilelmoussaoui** [comment]
Oh! Didn't knew that as the application doesn't really follow the GNOME releases schedule I thought it was a stable one. Especially that the NEWS file doesn't say it's a dev release.

**Comment by bilelmoussaoui** [comment]
Closing this one! Thanks for letting me know @kaiw

**Comment by kaiw** [comment]
Yeah, we don't follow the GNOME release schedule, though I've thought about trying before. We *do* follow odd/even version conventions. I think the NEWS format predates any notion that odd/even wasn't the 'normal' thing to do.

**Pull request closed without merging**
