### PR TITLE
Update to 3.18.3

### PR DESCRIPTION
**Pull request by Erick555**
Also update gtksourceview to 3.24.9. 
Also fixes https://github.com/flathub/org.gnome.meld/issues/9

### CODE REVIEW

**Comment by matthiasclasen** [comment]
Does this fix #9 ?

**Comment by Erick555** [comment]
I don't know, perhaps not. Here's the diff https://gitlab.gnome.org/GNOME/meld/compare/3.18.2...3.18.3

**Comment by matthiasclasen** [comment]
Doesn't look like it includes the 'rename everything' commit that fixed it upstream. Can we rename the file in the manifest ?

**Comment by Erick555** [comment]
It seems that devs won't add that commit to 3.18 branch: https://gitlab.gnome.org/GNOME/meld/merge_requests/4#note_223323

Could you tell me what should I do to fix it here?

**Comment by TingPing** [comment]
> Could you tell me what should I do to fix it here?

Just `mv` the `meld.xml` file to `org.gnome.meld`. And then if the file contains an icon name, `sed` that to `org.gnome.meld` too.

**Comment by Erick555** [comment]
I can look at it later. Feel free to commit to my branch yourself or add separate PR if you know exact fix already.

**Comment by Erick555** [comment]
@matthiasclasen @TingPing I added mime fix.

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
Builds successfully https://flathub.org/builds/#/builders/2/builds/6215
Thanks, everyone!

**Pull request merged**
